function createtable(A)
%CREATEOBJECT

%  Auto-generated by MATLAB on 15-May-2014 10:25:08
f = figure('Position',[20 20 542 100]);
 
cnames = {'Hibrid szimuláció'};
rnames = {'Elsõ szint alaktváltozása[m]','Elsõ szint abszolút elmozdulása[m]','Tetõponti elmozdulás[m]','Maximális nyíróerõ[kN]'};
uitable('Parent',f,'Data',A,'ColumnName',cnames,... 
            'RowName',rnames,'Position',[00 00 542 100]);

end


