function createtable(A)
%CREATEOBJECT

%  Auto-generated by MATLAB on 15-May-2014 10:25:08
f = figure('Position',[20 20 244 78]);
 
cnames = {'Nemlineáris'};
rnames = {'U_1^{max}','U_2^{max}','(U_2-U_1)^{max}'};
uitable('Parent',f,'Data',A,'ColumnName',cnames,... 
            'RowName',rnames,'Position',[00 00 244 78]);

end


