function createtable(A)
%CREATEOBJECT

%  Auto-generated by MATLAB on 15-May-2014 10:25:08
f = figure('Position',[20 20 636 400]);
 
cnames = {'t_i','U_1','U_2','U_{full,1}','U_{full,2}','U_{full,3}','U_{full,4}','U_{full,5}'};
% rnames = {'First','Second','Third'};
uitable('Parent',f,'Data',A,'ColumnName',cnames,... 
            'Position',[00 00 636 400]);

end


